### ISSUE TITLE
Updatesite contains nothing

### ISSUE THREAD

**Issue by zeromancer1972** [OpenNTF/XPagesExtLibX#12]
Reason: feature element contains wrong path to JAR file
correct value must be feature/org.openntf.extlibx.feature_9.0.1.v00_15_201512091510.jar
Timestamp is missing

**Comment by padraic-edwards** [comment]
Hi Oliver,
I have a fix, will patch the ExtLibX release and push a new zip to ExtLibX repo shortly.

Padraic

**Comment by zeromancer1972** [comment]
Great! Workaround in the meantime is to modify the value manually - so not a real problem
