### ISSUE TITLE
Pagers are broken due to refactored pagination CSS classes

### ISSUE THREAD

**Issue by briangleeson** [OpenNTF/XPagesExtLibX#8]
Due to this change in Bootstrap 4 alpha.2: https://github.com/twbs/bootstrap/pull/18110
Pagers require additional pager CSS classes in order to pick up Bootstrap4's pagination CSS. The pager renderers need to be updated with these new classes, as currently the pagers appear badly

**Comment by KOSNOWMAN** [comment]
Me too, I got terrible situation due to pagination. my other problem is that pager aligned vertical. So I tried to apply css(display:inline) but no effect. 
How to resolve this?

**Comment by briangleeson** [comment]
There is much work to be done to integrate Bootstrap4 with XPages. This issue is just one of the many tasks that will need to be tackled before BS4's release. In this case it will require changing the pager renderers to incorporate the new pager CSS classes, and possibly apply our own CSS tweaks as well.

The XPages team in IBM will be working on Bootstrap4 in XPages over the coming months, but you can also contribute code/fixes via this github repository. Check out the documentation in the latest release on openntf to see how: http://openntf.org/main.nsf/project.xsp?r=project/XPages%20ExtLibX/releases/FCB8D179C48D783486257F1E005BEF90

**Comment by KOSNOWMAN** [comment]
Thanks for related information. briangleeson. 
I provisionally solved that problems using alpha 1 ver stored my computer..
